api:
  debug: true
  host: 0.0.0.0
  port: 8080
  title: VPN User Manager
  version: 0.1.0

postgres:
  host: 127.0.0.1
  port: 5432
  database: user_manager_db
  username: user_manager_user
  pg_password: changeme_postgres
